### ISSUE TITLE
Screen rotation support

### ISSUE THREAD

**Issue by peternied** [MSOpenTech/msa-auth-for-android#4]
Can OAuthDialog can be converted into a DialogFragment in order to support screen rotations?

Traceback: https://github.com/OneDrive/onedrive-explorer-android/issues/52

**Comment by phileo** [comment]
Thanks @peternied for initiating this request.
I did some investigation, and as it turns out, using DialogFragments is not so practical because:
1. the OAuthConfig needs to be preserved across a dialog dismissal.
2. the DialogFragment cannot be an anonymous inner class

So keeping the current OAuthDialog inner class, I was able to modify AuthorizationRequest to support screen rotation.  If there is any interest, I can submit a pull request.

**Comment by joshgav** [comment]
We'd be happy to review a PR, sure.
